/* Code generated by httprpc. DO NOT EDIT. */

import type { ClientOptions } from './base'
import { request } from './base'
export type Anon = Record<string, never>
export interface Echo {
  message: string
}

export class ApiClient {
  constructor(private readonly opts: ClientOptions) {}
  async post_api_echo(req: Echo): Promise<Echo> {
    return request<Echo, Echo>(
      this.opts,
      "POST",
      "/api/echo",
      req,
      { 'Accept': "application/json", 'Content-Type': "application/json" },
    )
  }
  async get_api_ping(): Promise<Anon> {
    return request<Anon, Anon>(
      this.opts,
      "GET",
      "/api/ping",
      undefined,
      { 'Accept': "application/json" },
    )
  }
}
