/* Code generated by httprpc. DO NOT EDIT. */

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS' | 'HEAD'

export interface ClientOptions { baseUrl: string; fetch?: typeof fetch }

export const __httprpc_checksum = "b8a3f7857a0f4634903553358eb979faceb6768b885cbfab36bb134ee4af3051"

export async function request<TReq, TRes>(
  opts: ClientOptions,
  method: HttpMethod,
  path: string,
  body?: TReq,
  headers?: Record<string, string>,
): Promise<TRes> {
  const baseUrl = opts.baseUrl.replace(/\/$/, '')
  const fetchImpl = opts.fetch ?? fetch
  const url = baseUrl + path
  const res = await fetchImpl(url, {
    method,
    headers: {
      ...(body !== undefined ? { 'Content-Type': 'application/json' } : {}),
      ...(headers ?? {}),
    },
    body: body !== undefined ? JSON.stringify(body) : undefined,
  })
  if (!res.ok) {
    const text = await res.text().catch(() => '')
    throw new Error(text || res.statusText)
  }
  if (res.status === 204) return undefined as unknown as TRes
  return (await res.json()) as TRes
}
