/* Code generated by httprpc. DO NOT EDIT. */

import type { ClientOptions } from './base'
export type { ClientOptions, HttpMethod } from './base'
export { request } from './base'
export { __httprpc_checksum } from './base'
import { ApiClient } from './api'
export { ApiClient } from './api'

export class Client {
  readonly api: ApiClient

  constructor(opts: ClientOptions) {
    this.api = new ApiClient(opts)
  }
}
